#############################################################################
# Makefile for building: PRadEventViewer
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  QMakefile.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile QMakefile.pro
#############################################################################

MAKEFILE      = Makefile
####### Compiler, tools and options

CC            = gcc
CXX           = g++
CXXFLAGS      = -shared -pipe -std=c++11 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -Iinclude
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
LINK          = g++
LFLAGS        = -shared -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)
# -L$(ROOTSYS)/lib -lCore -lRint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lGui -lSpectrum -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Files

SOURCES       = src/ConfigParser.cpp \
                src/CAnalyzer.cpp \
                src/CMatrix.cpp

OBJECTS       = obj/ConfigParser.o \
                obj/CAnalyzer.o \
                obj/CMatrix.o

TARGET        = libCAna.so


OBJECTS_DIR   = obj

first: all
####### Build rules

$(TARGET):  $(OBJECTS)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

all: Makefile $(TARGET)

clean: cleanobj cleantgt

cleanobj:
	-$(DEL_FILE) $(OBJECTS)

cleantgt:
	-$(DEL_FILE) $(TARGET)

obj/ConfigParser.o: src/ConfigParser.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ConfigParser.o src/ConfigParser.cpp

obj/CAnalyzer.o: src/CAnalyzer.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CAnalyzer.o src/CAnalyzer.cpp

obj/CMatrix.o: src/CMatrix.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CMatrix.o src/CMatrix.cpp

####### Install

#install:   FORCE

#uninstall:   FORCE

#FORCE:


